### ISSUE TITLE
Count Down to Milestone

### ISSUE THREAD

**Issue by comaldave** [WealthInnovationsCA/WealthInnovationsCA-Hugo#4]
- [ ]  I have sent you in invite to join Davsk on Gitter. Please create an account and join. Let me know when you are in Universe.
- [ ] Be prepared to log in as Filmon on GitHub and on Cloudflare. It would be best if he owned the GitHub organization and created the workers that deployed the pages on Cloudflare. Be sure that you and I are both at super admin levels on both. If we have any problems with Filmon accounts then my fallback is to put it on your account. I cannot permit any additional traffic on my account.
- [ ] 2A Verify you have credentials for both accounts for Filmon.
- [ ] 2B We will transfer ownership on GitHub
- [ ] 2C We will go to Workers and Pages, General, press the green CTA and attach the repo to the demo subdomain.
- [ ] 2D Verify super admin rights have been granted.
- [ ]  You will need to ignore the home page but you will need to make an issue with a TODO for each page to verify that each page has been checked.
- [ ]  Copy the checklist to an issue to verify assets, as in pictures and icons
- [ ]  Copy the checklist to an issue to verify headers and table of contents are in place
- [ ]  Note any things that need to be edited. Note any style changes.
- [ ] We will review the heading and the footer after the pages are complete.
- [ ]  We need to design a new logo and banner, implement them on-site and provide for him to register them as service marks
- [ ] The last step is to design the home page.
