### ISSUE TITLE
You will need to ignore the home page but you will need to make an issue with a TODO for each page to verify that each page has been checked.

### ISSUE THREAD

**Issue by comaldave** [WealthInnovationsCA/WealthInnovationsCA-Hugo#5]

**Comment by comaldave** [comment]
➜  content git:(main) ✗ ls -R
.:

- [ ] /about     _index.md  legal   
- [ ] ./about:    index.md
- [ ] ./authors:   _index.md
- [ ] ./authors/filmon: _index.md  _index.zh-hans.md
- [ ] ./blog: index.md  
- [ ] ./blog/professional-incorporations: dental.md  index.md  medical.md
- [ ] ./categories: _index.md  _index.zh-hans.md
- [ ] ./contact:   index.md
- [ ] ./legal:    disclaimer.md   privacy.md   terms.md
- [ ] ./meet-with-me: index.md  
- [ ] ./services: index.md        Your_Financial_Library.md
- [ ] ./services/estate_planning: index.md  Succession_Planning.md  wills.md
- [ ] ./services/insurance:  Critical_Illness_Insurance.md   index.md
- [ ] './services/insurance/Disability Insurance': Buy-Out_Coverage.md  index.md  Overhead_Coverage.md  Personal.md
- [ ] './services/insurance/Life Insurance': index.md  Personal.md Insured_Retirement_Program.md  shareholders_agreement.md Key_Man_Insurance.md
- [ ] ./services/retirement: Government_Plans.md   Insured_Retirement_Policy.md _index.md  Retirement_Compensation_Agreement.md Individual_Pension_Plan.md
- [ ] ./services/tax_sheltering: Capital_Gains_Exemption_Planning.md  index.md Income_Splitting.md                 Tax_Free_Savings_Account.md
- [ ] ./solutions: exit_strategies.md  mid-career.md  rrsp.md   _index.md        retirement.md  start-up.md
- [ ] ./tags: _index.md  _index.zh-hans.md
